In [122]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [123]:
df1=pd.read_csv('Customer.csv')
df2=pd.read_csv('Product.csv')
df3=pd.read_csv('Transactions.csv')

In [124]:
df1.head()

   customer_Id         DOB Gender  city_code
0       268408  02-01-1970      M        4.0
1       269696  07-01-1970      F        8.0
2       268159  08-01-1970      F        8.0
3       270181  10-01-1970      F        2.0
4       268073  11-01-1970      M        1.0

In [125]:
df2.head()

   prod_cat_code  prod_cat  prod_sub_cat_code prod_subcat
0              1  Clothing                  4        Mens
1              1  Clothing                  1       Women
2              1  Clothing                  3        Kids
3              2  Footwear                  1        Mens
4              2  Footwear                  3       Women

In [126]:
df3.head()

,transaction_id,cust_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type
0,80712190438,270351,28-02-2014,1,1,-5,-772,405.300,-4265.300,e-Shop
1,29258453508,270384,27-02-2014,5,3,-5,-1497,785.925,-8270.925,e-Shop
2,51750724947,273420,24-02-2014,6,5,-2,-791,166.110,-1748.110,TeleShop
3,93274880719,271509,24-02-2014,11,6,-3,-1363,429.345,-4518.345,e-Shop
4,51750724947,273420,23-02-2014,6,5,-2,-791,166.110,-1748.110,TeleShop

In [127]:
df3['customer_Id']=df3['cust_id']
df3.drop('cust_id',axis=1,inplace=True)

In [128]:
df3.head()

,transaction_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,customer_Id
0,80712190438,28-02-2014,1,1,-5,-772,405.300,-4265.300,e-Shop,270351
1,29258453508,27-02-2014,5,3,-5,-1497,785.925,-8270.925,e-Shop,270384
2,51750724947,24-02-2014,6,5,-2,-791,166.110,-1748.110,TeleShop,273420
3,93274880719,24-02-2014,11,6,-3,-1363,429.345,-4518.345,e-Shop,271509
4,51750724947,23-02-2014,6,5,-2,-791,166.110,-1748.110,TeleShop,273420

In [129]:
df=pd.merge(left=df1,right=df3,on='customer_Id',how='inner')

In [130]:
df.head()

,customer_Id,DOB,Gender,city_code,transaction_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type
0,268408,02-01-1970,M,4.0,87243835584,13-01-2014,7,5,5,187,98.175,1033.175,TeleShop
1,268408,02-01-1970,M,4.0,16197868036,16-12-2013,1,4,-5,-210,110.250,-1160.250,Flagship store
2,268408,02-01-1970,M,4.0,16197868036,12/12/2013,1,4,5,210,110.250,1160.250,Flagship store
3,268408,02-01-1970,M,4.0,28810141075,2/9/2013,10,6,2,813,170.730,1796.730,TeleShop
4,268408,02-01-1970,M,4.0,64633435931,6/5/2013,4,2,3,312,98.280,1034.280,Flagship store

In [131]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23053 entries, 0 to 23052
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_Id       23053 non-null  int64
 1   DOB               23053 non-null  str
 2   Gender            23044 non-null  str
 3   city_code         23045 non-null  float64
 4   transaction_id    23053 non-null  int64
 5   tran_date         23053 non-null  str
 6   prod_subcat_code  23053 non-null  int64
 7   prod_cat_code     23053 non-null  int64
 8   Qty               23053 non-null  int64
 9   Rate              23053 non-null  int64
 10  Tax               23053 non-null  float64
 11  total_amt         23053 non-null  float64
 12  Store_type        23053 non-null  str
dtypes: float64(3), int64(6), str(4)
memory usage: 2.3 MB

In [132]:
df.isnull().sum()

customer_Id         0
DOB                 0
Gender              9
city_code           8
transaction_id      0
tran_date           0
prod_subcat_code    0
prod_cat_code       0
Qty                 0
Rate                0
Tax                 0
total_amt           0
Store_type          0
dtype: int64

In [133]:
df.dropna(inplace=True)

In [134]:
df['city_code']=df['city_code'].astype(int)

In [135]:
df.info()

<class 'pandas.DataFrame'>
Index: 23036 entries, 0 to 23052
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_Id       23036 non-null  int64
 1   DOB               23036 non-null  str
 2   Gender            23036 non-null  str
 3   city_code         23036 non-null  int64
 4   transaction_id    23036 non-null  int64
 5   tran_date         23036 non-null  str
 6   prod_subcat_code  23036 non-null  int64
 7   prod_cat_code     23036 non-null  int64
 8   Qty               23036 non-null  int64
 9   Rate              23036 non-null  int64
 10  Tax               23036 non-null  float64
 11  total_amt         23036 non-null  float64
 12  Store_type        23036 non-null  str
dtypes: float64(2), int64(7), str(4)
memory usage: 2.5 MB

In [136]:
df.columns

Index(['customer_Id', 'DOB', 'Gender', 'city_code', 'transaction_id',
       'tran_date', 'prod_subcat_code', 'prod_cat_code', 'Qty', 'Rate', 'Tax',
       'total_amt', 'Store_type'],
      dtype='str')

In [137]:
df.isnull().sum()

customer_Id         0
DOB                 0
Gender              0
city_code           0
transaction_id      0
tran_date           0
prod_subcat_code    0
prod_cat_code       0
Qty                 0
Rate                0
Tax                 0
total_amt           0
Store_type          0
dtype: int64

In [138]:
df.head()

,customer_Id,DOB,Gender,city_code,transaction_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type
0,268408,02-01-1970,M,4,87243835584,13-01-2014,7,5,5,187,98.175,1033.175,TeleShop
1,268408,02-01-1970,M,4,16197868036,16-12-2013,1,4,-5,-210,110.250,-1160.250,Flagship store
2,268408,02-01-1970,M,4,16197868036,12/12/2013,1,4,5,210,110.250,1160.250,Flagship store
3,268408,02-01-1970,M,4,28810141075,2/9/2013,10,6,2,813,170.730,1796.730,TeleShop
4,268408,02-01-1970,M,4,64633435931,6/5/2013,4,2,3,312,98.280,1034.280,Flagship store

In [139]:
df['prod_subcat_code'].value_counts()

prod_subcat_code
4     4001
3     3066
10    2990
1     2947
11    2055
12    2029
7     1042
2     1006
6      988
9      984
8      972
5      956
Name: count, dtype: int64

In [140]:
df['prod_cat_code'].value_counts()

prod_cat_code
5    6064
3    4894
6    4126
2    2998
1    2957
4    1997
Name: count, dtype: int64

In [141]:
df['Qty']=df['Qty'].apply(lambda x: x*-1 if x<0 else x)
df['Rate']=df['Rate'].apply(lambda x: x*-1 if x<0 else x)
df['Tax']=df['Tax'].apply(lambda x: x*-1 if x<0 else x)
df['total_amt']=df['total_amt'].apply(lambda x: x*-1 if x<0 else x)

In [142]:
df.head()

,customer_Id,DOB,Gender,city_code,transaction_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type
0,268408,02-01-1970,M,4,87243835584,13-01-2014,7,5,5,187,98.175,1033.175,TeleShop
1,268408,02-01-1970,M,4,16197868036,16-12-2013,1,4,5,210,110.250,1160.250,Flagship store
2,268408,02-01-1970,M,4,16197868036,12/12/2013,1,4,5,210,110.250,1160.250,Flagship store
3,268408,02-01-1970,M,4,28810141075,2/9/2013,10,6,2,813,170.730,1796.730,TeleShop
4,268408,02-01-1970,M,4,64633435931,6/5/2013,4,2,3,312,98.280,1034.280,Flagship store

In [143]:
df[df['total_amt']<0]

Empty DataFrame
Columns: [customer_Id, DOB, Gender, city_code, transaction_id, tran_date, prod_subcat_code, prod_cat_code, Qty, Rate, Tax, total_amt, Store_type]
Index: []

In [144]:
df['Store_type'].value_counts()

Store_type
e-Shop            9306
MBR               4659
Flagship store    4575
TeleShop          4496
Name: count, dtype: int64

In [145]:
df['customer_Id'].value_counts()

customer_Id
269449    13
268819    13
266794    12
269245    12
273014    12
          ..
268051     1
273263     1
270249     1
268483     1
270580     1
Name: count, Length: 5502, dtype: int64

In [146]:
df['DOB'].value_counts()

DOB
17-09-1982    32
27-12-1988    32
25-02-1974    27
20-03-1972    25
09-06-1970    24
              ..
23-04-1992     1
08-06-1992     1
17-06-1992     1
29-07-1992     1
01-09-1992     1
Name: count, Length: 3984, dtype: int64

In [147]:
df['Date_Of_Birth']=df['DOB'].str.split('-').str[0].astype(int)
df['Month_Of_Birth']=df['DOB'].str.split('-').str[1].astype(int)
df['Year_Of_Birth']=df['DOB'].str.split('-').str[2].astype(int)

In [148]:
df.head(5)

,customer_Id,DOB,Gender,city_code,transaction_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,Date_Of_Birth,Month_Of_Birth,Year_Of_Birth
0,268408,02-01-1970,M,4,87243835584,13-01-2014,7,5,5,187,98.175,1033.175,TeleShop,2,1,1970
1,268408,02-01-1970,M,4,16197868036,16-12-2013,1,4,5,210,110.250,1160.250,Flagship store,2,1,1970
2,268408,02-01-1970,M,4,16197868036,12/12/2013,1,4,5,210,110.250,1160.250,Flagship store,2,1,1970
3,268408,02-01-1970,M,4,28810141075,2/9/2013,10,6,2,813,170.730,1796.730,TeleShop,2,1,1970
4,268408,02-01-1970,M,4,64633435931,6/5/2013,4,2,3,312,98.280,1034.280,Flagship store,2,1,1970

In [149]:
df['tran_date'] = pd.to_datetime(df['tran_date'], dayfirst=True,format='mixed')

df['Transaction_Date'] = df['tran_date'].dt.day
df['Transaction_Month'] = df['tran_date'].dt.month
df['Transaction_Year'] = df['tran_date'].dt.year

In [150]:
df.head()

,customer_Id,DOB,Gender,city_code,transaction_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,Date_Of_Birth,Month_Of_Birth,Year_Of_Birth,Transaction_Date,Transaction_Month,Transaction_Year
0,268408,02-01-1970,M,4,87243835584,2014-01-13,7,5,5,187,98.175,1033.175,TeleShop,2,1,1970,13,1,2014
1,268408,02-01-1970,M,4,16197868036,2013-12-16,1,4,5,210,110.250,1160.250,Flagship store,2,1,1970,16,12,2013
2,268408,02-01-1970,M,4,16197868036,2013-12-12,1,4,5,210,110.250,1160.250,Flagship store,2,1,1970,12,12,2013
3,268408,02-01-1970,M,4,28810141075,2013-09-02,10,6,2,813,170.730,1796.730,TeleShop,2,1,1970,2,9,2013
4,268408,02-01-1970,M,4,64633435931,2013-05-06,4,2,3,312,98.280,1034.280,Flagship store,2,1,1970,6,5,2013

In [151]:
df.drop(['DOB','tran_date'],axis=1,inplace=True)

In [152]:
df.info()

<class 'pandas.DataFrame'>
Index: 23036 entries, 0 to 23052
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_Id        23036 non-null  int64
 1   Gender             23036 non-null  str
 2   city_code          23036 non-null  int64
 3   transaction_id     23036 non-null  int64
 4   prod_subcat_code   23036 non-null  int64
 5   prod_cat_code      23036 non-null  int64
 6   Qty                23036 non-null  int64
 7   Rate               23036 non-null  int64
 8   Tax                23036 non-null  float64
 9   total_amt          23036 non-null  float64
 10  Store_type         23036 non-null  str
 11  Date_Of_Birth      23036 non-null  int64
 12  Month_Of_Birth     23036 non-null  int64
 13  Year_Of_Birth      23036 non-null  int64
 14  Transaction_Date   23036 non-null  int32
 15  Transaction_Month  23036 non-null  int32
 16  Transaction_Year   23036 non-null  int32
dtypes: float64(2), int32(3), int64(10), str(2)
memory usage: 2.9 MB

In [153]:
df['Store_type'].value_counts()

Store_type
e-Shop            9306
MBR               4659
Flagship store    4575
TeleShop          4496
Name: count, dtype: int64

In [154]:
df['Store_type'].unique()

<StringArray>
['TeleShop', 'Flagship store', 'e-Shop', 'MBR']
Length: 4, dtype: str

In [155]:
df.head()

,customer_Id,Gender,city_code,transaction_id,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,Date_Of_Birth,Month_Of_Birth,Year_Of_Birth,Transaction_Date,Transaction_Month,Transaction_Year
0,268408,M,4,87243835584,7,5,5,187,98.175,1033.175,TeleShop,2,1,1970,13,1,2014
1,268408,M,4,16197868036,1,4,5,210,110.250,1160.250,Flagship store,2,1,1970,16,12,2013
2,268408,M,4,16197868036,1,4,5,210,110.250,1160.250,Flagship store,2,1,1970,12,12,2013
3,268408,M,4,28810141075,10,6,2,813,170.730,1796.730,TeleShop,2,1,1970,2,9,2013
4,268408,M,4,64633435931,4,2,3,312,98.280,1034.280,Flagship store,2,1,1970,6,5,2013

In [156]:
def encode_Stores(store:str) -> int:
    if store=='e-Shop':
        return 1
    elif store=='MBR':
        return 2
    elif store=='Flagship store':
        return 3
    elif store=='TeleShop':
        return 4

In [157]:
df['Gender_encoded']=df['Gender'].apply(lambda x: 1 if x=='M' else 0)
df['Store_type_encoded']=df['Store_type'].apply(encode_Stores)

In [158]:
df.head()

,customer_Id,Gender,city_code,transaction_id,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,Date_Of_Birth,Month_Of_Birth,Year_Of_Birth,Transaction_Date,Transaction_Month,Transaction_Year,Gender_encoded,Store_type_encoded
0,268408,M,4,87243835584,7,5,5,187,98.175,1033.175,TeleShop,2,1,1970,13,1,2014,1,4
1,268408,M,4,16197868036,1,4,5,210,110.250,1160.250,Flagship store,2,1,1970,16,12,2013,1,3
2,268408,M,4,16197868036,1,4,5,210,110.250,1160.250,Flagship store,2,1,1970,12,12,2013,1,3
3,268408,M,4,28810141075,10,6,2,813,170.730,1796.730,TeleShop,2,1,1970,2,9,2013,1,4
4,268408,M,4,64633435931,4,2,3,312,98.280,1034.280,Flagship store,2,1,1970,6,5,2013,1,3

In [159]:
df.drop(columns=['Gender','Store_type'],inplace=True)

In [160]:
df['Store_type_encoded']=df['Store_type_encoded'].astype(int)

In [161]:
df.head()

,customer_Id,city_code,transaction_id,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Date_Of_Birth,Month_Of_Birth,Year_Of_Birth,Transaction_Date,Transaction_Month,Transaction_Year,Gender_encoded,Store_type_encoded
0,268408,4,87243835584,7,5,5,187,98.175,1033.175,2,1,1970,13,1,2014,1,4
1,268408,4,16197868036,1,4,5,210,110.250,1160.250,2,1,1970,16,12,2013,1,3
2,268408,4,16197868036,1,4,5,210,110.250,1160.250,2,1,1970,12,12,2013,1,3
3,268408,4,28810141075,10,6,2,813,170.730,1796.730,2,1,1970,2,9,2013,1,4
4,268408,4,64633435931,4,2,3,312,98.280,1034.280,2,1,1970,6,5,2013,1,3

In [163]:
df.drop('transaction_id',axis=1,inplace=True)

In [164]:
df.head()

,customer_Id,city_code,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Date_Of_Birth,Month_Of_Birth,Year_Of_Birth,Transaction_Date,Transaction_Month,Transaction_Year,Gender_encoded,Store_type_encoded
0,268408,4,7,5,5,187,98.175,1033.175,2,1,1970,13,1,2014,1,4
1,268408,4,1,4,5,210,110.250,1160.250,2,1,1970,16,12,2013,1,3
2,268408,4,1,4,5,210,110.250,1160.250,2,1,1970,12,12,2013,1,3
3,268408,4,10,6,2,813,170.730,1796.730,2,1,1970,2,9,2013,1,4
4,268408,4,4,2,3,312,98.280,1034.280,2,1,1970,6,5,2013,1,3

In [166]:
df.info()

<class 'pandas.DataFrame'>
Index: 23036 entries, 0 to 23052
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_Id         23036 non-null  int64
 1   city_code           23036 non-null  int64
 2   prod_subcat_code    23036 non-null  int64
 3   prod_cat_code       23036 non-null  int64
 4   Qty                 23036 non-null  int64
 5   Rate                23036 non-null  int64
 6   Tax                 23036 non-null  float64
 7   total_amt           23036 non-null  float64
 8   Date_Of_Birth       23036 non-null  int64
 9   Month_Of_Birth      23036 non-null  int64
 10  Year_Of_Birth       23036 non-null  int64
 11  Transaction_Date    23036 non-null  int32
 12  Transaction_Month   23036 non-null  int32
 13  Transaction_Year    23036 non-null  int32
 14  Gender_encoded      23036 non-null  int64
 15  Store_type_encoded  23036 non-null  int64
dtypes: float64(2), int32(3), int64(11)
memory usage: 2.7 MB

In [168]:
df.isnull().sum()

customer_Id           0
city_code             0
prod_subcat_code      0
prod_cat_code         0
Qty                   0
Rate                  0
Tax                   0
total_amt             0
Date_Of_Birth         0
Month_Of_Birth        0
Year_Of_Birth         0
Transaction_Date      0
Transaction_Month     0
Transaction_Year      0
Gender_encoded        0
Store_type_encoded    0
dtype: int64

In [170]:
df.to_csv('Retail_Case_Study_Cleaned.csv',index=False)